src/Entity/Contact.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactRepository")
 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 5,
     *      max = 100,
     *      minMessage = "Le titre doit faire plus de {{ limit }} caracters.",
     *      maxMessage = "Le titre doit faire moins de {{ limit }} caracters."
     * )
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 10,
     *      max = 120,
     *      minMessage = "Votre mail doit faire plus de {{ limit }} caracters.",
     *      maxMessage = "Votre mail doit faire moins de {{ limit }} caracters."
     * )
     */
    private $mail;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 20,
     *      max = 800,
     *      minMessage = "Votre demande doit faire plus de {{ limit }} caracters.",
     *      maxMessage = "Votre demande doit faire moins de {{ limit }} caracters."
     * )
     */
    private $resquest;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $raison_sociale;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getResquest(): ?string
    {
        return $this->resquest;
    }

    public function setResquest(string $resquest): self
    {
        $this->resquest = $resquest;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }

    public function setRaisonSociale(string $raison_sociale): self
    {
        $this->raison_sociale = $raison_sociale;

        return $this;
    }
}

src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre', TextType::class)
            ->add('mail', EmailType::class)
            ->add('resquest', TextareaType::class)
            ->add('raison_sociale', TextType::class, array(
              'required' => false,
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ContactRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use JasonGrimes\Paginator;

/**
 * @Route("admin/contact")
 */
class ContactController extends AbstractController
{
    /**
     * @Route("/", name="contact_index", methods={"GET"})
     */
    public function index(ContactRepository $contactRepository, Request $request): Response
    {
      $totalItems = $contactRepository->countContact();
      $itemsPerPage = 10;
      $currentPage = $request->query->get('page', 1);
      $urlPattern = '?page=(:num)';
      $limit = 10;
      $offset = ($currentPage * $limit) - $limit;

      $paginator = new Paginator($totalItems, $itemsPerPage, $currentPage, $urlPattern);

      return $this->render('contact/index.html.twig', [
          'contacts' => $contactRepository->selectManyContact($offset),
          'paginator' => $paginator,
      ]);
    }

    /**
     * @Route("/new", name="contact_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contact);
            $entityManager->flush();

            return $this->redirectToRoute('contact_index');
        }

        return $this->render('contact/new.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="contact_show", methods={"GET"})
     */
    public function show(Contact $contact): Response
    {
        return $this->render('contact/show.html.twig', [
            'contact' => $contact,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="contact_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Contact $contact): Response
    {
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('contact_index', [
                'id' => $contact->getId(),
            ]);
        }

        return $this->render('contact/edit.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="contact_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Contact $contact): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contact->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($contact);
            $entityManager->flush();
        }

        return $this->redirectToRoute('contact_index');
    }
}

templates/contact/_delete_form.html.twig
<form method="post" action="{{ path('contact_delete', {'id': contact.id}) }}" onsubmit="return confirm('Etes vous sure de vouloir supprimer ceci ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/contact/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Contact index{% endblock %}

{% block body %}
    <h1>Listes des contacts</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Mail</th>
                <th>Demande/th>
                <th>Détail</th>
                <th>Suppression</th>
            </tr>
        </thead>
        <tbody>
        {% for contact in contacts %}
            <tr>
                <td>{{ contact.titre }}</td>
                <td>{{ contact.mail }}</td>
                <td>{{ contact.resquest|striptags|slice(0, 30)|raw }}</td>
                <td><a class="btn btn-info" href="{{ path('contact_show', {'id': contact.id}) }}">Détail</a></td>
                <td>{{ include('contact/_delete_form.html.twig') }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ paginator|raw }}

{% endblock %}

templates/contact/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}
    <h1>Contact</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Titre</th>
                <td>{{ contact.titre }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ contact.mail }}</td>
            </tr>
            <tr>
                <th>Resquest</th>
                <td>{{ contact.resquest }}</td>
            </tr>
            <tr>
                <th>Raison_sociale</th>
                <td>{{ contact.raisonSociale }}</td>
            </tr>
        </tbody>
    </table>

    {{ include('contact/_delete_form.html.twig') }}
{% endblock %}