src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 5,
     *      max = 100,
     *      minMessage = "Le titre doit faire plus de {{ limit }} caracters.",
     *      maxMessage = "Le titre doit faire moins de {{ limit }} caracters."
     * )
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 30,
     *      max = 3500,
     *      minMessage = "Le texte doit faire plus de {{ limit }} caracters.",
     *      maxMessage = "Le texte doit faire moins de {{ limit }} caracters."
     * )
     */
    private $texte;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_video;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_video2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_video3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_video4;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_img;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_img2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_img3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_img4;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_sound;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_sound2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_sound3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_sound4;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\NotBlank
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Commentaire", inversedBy="id_article")
     */
    private $commentaire;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(?string $texte): self
    {
        $this->texte = $texte;

        return $this;
    }

    public function getUrlVideo(): ?string
    {
        return $this->url_video;
    }

    public function setUrlVideo(?string $url_video): self
    {
        $this->url_video = $url_video;

        return $this;
    }

    public function getUrlVideo2(): ?string
    {
        return $this->url_video2;
    }

    public function setUrlVideo2(?string $url_video2): self
    {
        $this->url_video2 = $url_video2;

        return $this;
    }

    public function getUrlVideo3(): ?string
    {
        return $this->url_video3;
    }

    public function setUrlVideo3(?string $url_video3): self
    {
        $this->url_video3 = $url_video3;

        return $this;
    }

    public function getUrlVideo4(): ?string
    {
        return $this->url_video4;
    }

    public function setUrlVideo4(?string $url_video4): self
    {
        $this->url_video4 = $url_video4;

        return $this;
    }

    public function getUrlImg(): ?string
    {
        return $this->url_img;
    }

    public function setUrlImg(?string $url_img): self
    {
        $this->url_img = $url_img;

        return $this;
    }

    public function getUrlImg2(): ?string
    {
        return $this->url_img2;
    }

    public function setUrlImg2(?string $url_img2): self
    {
        $this->url_img2 = $url_img2;

        return $this;
    }

    public function getUrlImg3(): ?string
    {
        return $this->url_img3;
    }

    public function setUrlImg3(?string $url_img3): self
    {
        $this->url_img3 = $url_img3;

        return $this;
    }

    public function getUrlImg4(): ?string
    {
        return $this->url_img4;
    }

    public function setUrlImg4(?string $url_img4): self
    {
        $this->url_img4 = $url_img4;

        return $this;
    }

    public function getUrlSound(): ?string
    {
        return $this->url_sound;
    }

    public function setUrlSound(?string $url_sound): self
    {
        $this->url_sound = $url_sound;

        return $this;
    }

    public function getUrlSound2(): ?string
    {
        return $this->url_sound2;
    }

    public function setUrlSound2(?string $url_sound2): self
    {
        $this->url_sound2 = $url_sound2;

        return $this;
    }

    public function getUrlSound3(): ?string
    {
        return $this->url_sound3;
    }

    public function setUrlSound3(?string $url_sound3): self
    {
        $this->url_sound3 = $url_sound3;

        return $this;
    }

    public function getUrlSound4(): ?string
    {
        return $this->url_sound4;
    }

    public function setUrlSound4(?string $url_sound4): self
    {
        $this->url_sound4 = $url_sound4;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCommentaire(): ?Commentaire
    {
        return $this->commentaire;
    }

    public function setCommentaire(?Commentaire $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre', TextType::class)
            ->add('texte', TextareaType::class)
            ->add('url_video', UrlType::class)
            ->add('url_video2', UrlType::class)
            ->add('url_video3', UrlType::class)
            ->add('url_video4', UrlType::class)
            ->add('url_img', UrlType::class)
            ->add('url_img2', UrlType::class)
            ->add('url_img3', UrlType::class)
            ->add('url_img4', UrlType::class)
            ->add('url_sound', UrlType::class)
            ->add('url_sound2', UrlType::class)
            ->add('url_sound3', UrlType::class)
            ->add('url_sound4', UrlType::class)
            ->add('type', ChoiceType::class, array(
              'choices'  => [
                      'article'    => 'article',
                      'news'       => 'news',
                      'video'      => 'video',
                      'galerie'    => 'galerie',
                ],
                'expanded' => true,
            ))
            ->add('status', ChoiceType::class, array(
              'choices'  => [
                      'publié'    => 'publié',
                      'brouillon' => 'brouillon',
                      'poubelle'  => 'poubelle'
                ],
                'expanded' => true,
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use JasonGrimes\Paginator;

/**
 * @Route("admin/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository, Request $request): Response
    {
        $totalItems = $articleRepository->countArticle();
        $itemsPerPage = 10;
        $currentPage = $request->query->get('page', 1);
        $urlPattern = '?page=(:num)';
        $limit = 10;
        $offset = ($currentPage * $limit) - $limit;

        $paginator = new Paginator($totalItems, $itemsPerPage, $currentPage, $urlPattern);

        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->selectManyArticle($offset),
            'paginator' => $paginator,
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_index', [
                'id' => $article->getId(),
            ]);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Etes vous sure de vouloir supprimer ceci ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Editer l'article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Sauvegarder'}) }}
{% endblock %}

templates/article/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <h1>Liste des articles <a class="btn btn-info" href="{{ path('article_new') }}">Créer un nouvelle article</a></h1>

    <table class="table">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Status</th>
                <th>Details</th>
                <th>Editidion</th>
                <th>Supression</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.titre }}</td>
                <td>{{ article.status }}</td>
                <td><a class="btn btn-info" href="{{ path('article_show', {'id': article.id}) }}">show</a></td>
                <td><a class="btn btn-success" href="{{ path('article_edit', {'id': article.id}) }}">edit</a></td>
                <td>{{ include('article/_delete_form.html.twig') }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="19">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ paginator|raw }}

{% endblock %}

templates/article/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Créer un nouvelle article</h1>

    {{ include('article/_form.html.twig') }}
{% endblock %}

templates/article/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Détails de l'article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ article.titre }}</td>
            </tr>
            <tr>
                <th>Texte</th>
                <td>{{ article.texte }}</td>
            </tr>
            <tr>
                <th>Url_video</th>
                <td>{{ article.urlVideo }}</td>
            </tr>
            <tr>
                <th>Url_video2</th>
                <td>{{ article.urlVideo2 }}</td>
            </tr>
            <tr>
                <th>Url_video3</th>
                <td>{{ article.urlVideo3 }}</td>
            </tr>
            <tr>
                <th>Url_video4</th>
                <td>{{ article.urlVideo4 }}</td>
            </tr>
            <tr>
                <th>Url_img</th>
                <td>{{ article.urlImg }}</td>
            </tr>
            <tr>
                <th>Url_img2</th>
                <td>{{ article.urlImg2 }}</td>
            </tr>
            <tr>
                <th>Url_img3</th>
                <td>{{ article.urlImg3 }}</td>
            </tr>
            <tr>
                <th>Url_img4</th>
                <td>{{ article.urlImg4 }}</td>
            </tr>
            <tr>
                <th>Url_sound</th>
                <td>{{ article.urlSound }}</td>
            </tr>
            <tr>
                <th>Url_sound2</th>
                <td>{{ article.urlSound2 }}</td>
            </tr>
            <tr>
                <th>Url_sound3</th>
                <td>{{ article.urlSound3 }}</td>
            </tr>
            <tr>
                <th>Url_sound4</th>
                <td>{{ article.urlSound4 }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ article.updatedAt ? article.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ article.status }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('article_edit', {'id': article.id}) }}">Edité l'article</a>
{% endblock %}